# Generated by Django 4.1.4 on 2023-01-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_indexes_delete_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='<django.db.models.fields.CharField>@uoregon.edu', max_length=254),
        ),
    ]
