# Generated by Django 4.1.4 on 2023-01-01 05:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateField(default=datetime.date(2022, 12, 31)),
        ),
    ]
