# Generated by Django 4.1.4 on 2023-01-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_join_date_pirg_created_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_pi',
        ),
    ]
