# Generated by Django 4.1.4 on 2023-01-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_is_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pi',
            field=models.BooleanField(default=False),
        ),
    ]
