# Generated by Django 4.1.4 on 2023-01-01 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_sponsor_user_is_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
