# Generated by Django 4.1.7 on 2023-02-16 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_email_alter_user_is_pi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirg',
            name='admins',
            field=models.ManyToManyField(related_name='pirg_admins', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='pirg',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pirg_owner', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='pirg',
            name='users',
            field=models.ManyToManyField(related_name='pirg_users', to='accounts.user'),
        ),
    ]
